/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface SharedAnalyticsData {
  'totalDuration' : bigint,
  'averageDuration' : bigint,
  'totalPageViews' : bigint,
  'sections' : Array<[string, SharedSectionAnalytics]>,
  'modulePageViews' : Array<[string, bigint]>,
}
export interface SharedSectionAnalytics {
  'averageScrollDepth' : bigint,
  'totalViews' : bigint,
  'totalScrollDepth' : bigint,
  'totalDuration' : bigint,
  'averageDuration' : bigint,
}
export interface Subscriber { 'name' : string, 'email' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getAnalyticsData' : ActorMethod<[], SharedAnalyticsData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribed' : ActorMethod<[string], boolean>,
  'recordModulePageView' : ActorMethod<[string], undefined>,
  'recordPageView' : ActorMethod<[bigint], undefined>,
  'recordSectionView' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribe' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];