/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subscriber = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
export const SharedSectionAnalytics = IDL.Record({
  'averageScrollDepth' : IDL.Nat,
  'totalViews' : IDL.Nat,
  'totalScrollDepth' : IDL.Nat,
  'totalDuration' : IDL.Nat,
  'averageDuration' : IDL.Nat,
});
export const SharedAnalyticsData = IDL.Record({
  'totalDuration' : IDL.Nat,
  'averageDuration' : IDL.Nat,
  'totalPageViews' : IDL.Nat,
  'sections' : IDL.Vec(IDL.Tuple(IDL.Text, SharedSectionAnalytics)),
  'modulePageViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getAnalyticsData' : IDL.Func([], [SharedAnalyticsData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'recordModulePageView' : IDL.Func([IDL.Text], [], []),
  'recordPageView' : IDL.Func([IDL.Nat], [], []),
  'recordSectionView' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribe' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subscriber = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const SharedSectionAnalytics = IDL.Record({
    'averageScrollDepth' : IDL.Nat,
    'totalViews' : IDL.Nat,
    'totalScrollDepth' : IDL.Nat,
    'totalDuration' : IDL.Nat,
    'averageDuration' : IDL.Nat,
  });
  const SharedAnalyticsData = IDL.Record({
    'totalDuration' : IDL.Nat,
    'averageDuration' : IDL.Nat,
    'totalPageViews' : IDL.Nat,
    'sections' : IDL.Vec(IDL.Tuple(IDL.Text, SharedSectionAnalytics)),
    'modulePageViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getAnalyticsData' : IDL.Func([], [SharedAnalyticsData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'recordModulePageView' : IDL.Func([IDL.Text], [], []),
    'recordPageView' : IDL.Func([IDL.Nat], [], []),
    'recordSectionView' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribe' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };